dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11

env:
  global:
    - DEPLOY_JDK=openjdk8
    - DEPLOY_REPO=nbbrd/jdemetra-dotstat
    - DEPLOY_BIN=demetra-dotstat-desktop/target/binaries/*

deploy:
  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    draft: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

cache:
  directories:
    - $HOME/.m2
